[package]
name = "anyml"
version = "0.0.0"
edition = "2024"

[dependencies]
anyml_core = { path = "./crates/anyml_core" }
anyml_anthropic = { path = "./crates/anyml_anthropic", optional = true }
anyml_ollama = { path = "./crates/anyml_ollama", optional = true }
anyml_openai = { path = "./crates/anyml_openai", optional = true }

[features]
default = []
full = ["anthropic", "ollama", "openai"]
anthropic = ["dep:anyml_anthropic"]
ollama = ["dep:anyml_ollama"]
openai = ["dep:anyml_openai"]


[workspace]
members = [
    "crates/anyml_ollama",
    "crates/anyml_anthropic",
    "crates/anyml_openai",
    "crates/anyml_core"
]
